[build]
  command = "npm install -g allure-commandline && allure generate . --clean -o netlify_reports/allure-report && ntli build -a"
  publish = "netlify_reports/allure-report"

[functions]
  directory = ".ntli/site/netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/allure-report/*"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[dev]
  autoLaunch = false
  functions = ".ntli/site/netlify/functions"
  publish = "netlify_reports/allure-report"
