name: Deploy to Netlify

on:
  push:
    branches:
      - main # змініть на вашу гілку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        uses: netlify/actions/cli@2.0.10 # Замініть на потрібну версію
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
