name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
        # You may need to adjust this installation based on your specific environment.

      - name: Install dependencies
        run: |
          cd /home/runner/work/TestFolio/TestFolio
          pip install -r requirements.txt
        working-directory: /home/runner/work/TestFolio/TestFolio

      - name: Run tests and generate Allure report
        run: |
          cd /home/runner/work/TestFolio/TestFolio
          # Specify the full path to allure_pytest
          /path/to/allure_pytest --alluredir=/home/runner/work/TestFolio/TestFolio/allure-results/$(date +\%Y-\%m-\%d_\%H-\%M-\%S)
        working-directory: /home/runner/work/TestFolio/TestFolio

      - name: Serve Allure report
        run: |
          cd /home/runner/work/TestFolio/TestFolio
          # Serve the Allure report from the specified directory
          allure serve allure-results/$(date +\%Y-\%m-\%d_\%H-\%M-\%S)
        working-directory: /home/runner/work/TestFolio/TestFolio

      - name: Kill Chrome Processes
        run: pkill chrome || true
